name: Trigger Drone CI

on:
  issue_comment:
    types: [created]

jobs:
  trigger_drone_ci:
    if: contains(github.event.comment.body, 'rodar drone')
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: erro-semantico
          message: |
            Essa é uma menssagem teste
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
